server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # 紀錄讀取進度，避免重啟時重複發送

clients:
  - url: http://loki:3100/loki/api/v1/push 

scrape_configs:
  # 收集試題 1 (爬蟲) 的 Log
  - job_name: 'scraper_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'scraper_logs'
          __path__: /var/log/task1/*.log

  # 收集試題 2 (API) 的 Log
  - job_name: 'api_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'api_logs'
          __path__: /var/log/task2/*.log